model:
  list: ["03", "05", "07", "10", "12", "16"]

control_rate: 500 # Hz

home_joint_positions:
  defaults:
    shoulder_pan_joint: 0.0 # °
    shoulder_lift_joint: -90.0 # °
    elbow_joint: 0.0 # °
    wrist_1_joint: -90.0 # °
    wrist_2_joint: 0.0 # °
    wrist_3_joint: 0.0 # °
